[package]
name = "replace_tags"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
imagemeta = "0.1.0"
img-parts = "0.3.0"
clap = { version = "*", features = ["derive"] }
